version: '3.1'

volumes:
  db-data:
    driver: local
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - PGUSER=desertfox
      - POSTGRES_USER=desertfox
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=localData
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_INITDB_ARGS=--auth-host=trust
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    container_name: sulf
    image: sulf
    build: ./
    ports:
      - "8089:8089"
    depends_on:
      - db